# Use dummy language to suppress Haskell-specific, automatic build steps
# (will be done inside dev container)
language: cpp
sudo: required
services:
  - docker
dist: trusty

cache:
  directories:
    - /home/travis/build/bbiskup/cilia/.ghc
    - /home/travis/build/bbiskup/cilia/.cabal
    - /home/travis/build/bbiskup/cilia/.stack

before_script:
  - pwd
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./scripts/bootstrap.sh

