# Use dummy language to suppress Haskell-specific, automatic build steps
# (will be done inside dev container)
language: cpp
sudo: required
services:
  - docker
dist: trusty

addons:
  artifacts:
    debug: true
    s3_region: "eu-central-1"
    bucket: "cilia-deb"
    paths:
      - ./debian-build/cilia.deb

cache:
  directories:
    - /home/travis/build/bbiskup/cilia/.ghc
    - /home/travis/build/bbiskup/cilia/.cabal
    - /home/travis/build/bbiskup/cilia/.cabal-sandbox
    - /home/travis/build/bbiskup/cilia/.stack
    # - /home/travis/.travis-docker

before_script:
  - pwd
  - du -sh .ghc
  - du -sh .cabal
  - du -sh .cabal-sandbox
  # - du -sh ~/.travis-docker/
  # - if [[ -e ~/.travis-docker/dev-image.tar ]]; then echo "Loading cached dev image"; docker load -i ~/.travis-docker/dev-image.tar; fi
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./scripts/bootstrap.sh
  # - mkdir -p ~/.travis-docker; docker save cilia_dev > ~/.travis-docker/dev-image.tar

script:
  - make build
  - make create-minimal-docker-container
  - make test
  - make build-debian-package
  - make docker-push

