language: haskell
sudo: required
services:
  - docker
dist: trusty

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_script:
  - pwd
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./scripts/bootstrap.sh

