FROM haskell:7.10.3
MAINTAINER bbiskup@gmx.de

RUN apt-get -yy update && \
    apt-get install -yy \
        python python-pip rsync libltdl7 \
        threadscope libghc-ghc-events-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install dockerize==0.2.2

RUN useradd -m -s /bin/bash cilia
WORKDIR /home/cilia

RUN cabal update

ADD LICENSE LICENSE
ADD ./src src

# RUN cabal install

ENV PATH=$PATH:/home/cilia/.cabal-sandbox/bin:/home/cilia/dist/build/


ENTRYPOINT  ["/bin/bash", "-c"]