version: '2'
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile.cilia-dev
        network_mode: host
        volumes:
            - .:/home/cilia
            - ./examples/cilia.yml:/root/cilia.yml

            # - ./src:/home/cilia/src
            # - ./src-lib:/home/cilia/src-lib
            # - ./test:/home/cilia/test
            # - .bash_history:/home/cilia/.bash_history
            # - ./.cabal:/home/cilia/.cabal
            # - ./cilia.cabal:/home/cilia/cilia.cabal
            # # - ./cabal.sandbox.config:/home/cilia/cabal.sandbox.config
            # - ./.cabal-sandbox:/home/cilia/.cabal-sandbox
            # - ./dist:/home/cilia/dist
            # - ./examples/cilia.yml:/root/cilia.yml

            # Access to Docker daemon on host
            # - /usr/bin/docker:/usr/bin/docker
            # - /var/run/docker.sock:/var/run/docker.sock
