version: '2'
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile.cilia-dev
        network_mode: host
        volumes:
            - .:/home/cilia
            - ./examples/cilia.yml:/root/cilia.yml

            # Access to Docker daemon on host
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock

        environment:
            - PATH:$PATH:/home/cilia/.cabal-sandbox/bin

