version: '2'
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile.cilia-dev
        network_mode: host
        volumes:
            # - ./data:/data
            - ./examples/cilia.yml:/home/cilia/cilia.yml